### ISSUE TITLE
Cannot read properties of undefined (reading 'transient')

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#10417]
### How to reproduce the issue?

Select street level image (Mapillary, regardless of single image or 360)
Select building. (toggles 'set photo from viewer' button, which is missing translation)
![image](https://github.com/user-attachments/assets/940dc59f-0c94-4a13-8f53-e939e85e9f9f)
Move building. Map glitches out. Returns the following error

```
id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:13318)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5711
    at Array.map (<anonymous>)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5701)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:6640)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:8316
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at a.gatherStats (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:9065)
    at a (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:21910)
    at u (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:24770)
```

Similar errors returned when i.e. moving an object in this state.

```
id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:13318)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5711
    at Array.map (<anonymous>)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5701)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:6640)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:8378
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at a (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6457)
    at n (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6235)
    at Object.perform (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:7120)
```
```
22id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:13318)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5711
    at Array.map (<anonymous>)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5701)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:6640)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:8378
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at a (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6457)
    at r (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6296)
    at Object.replace (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:7429)
```
```
id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59 Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:13318)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5711
    at Array.map (<anonymous>)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5701)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:6640)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:8378
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at a (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6457)
    at Object.undo (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:7822)
    at Object.undo (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:27:23797)
```
(same for redo action)

Subsequent occasional issues
- Editor gets stuck in the preset menu, though the preset is succesfully applied.
- Values added in object fields might not be applied.
- 'tag this photo id on the currently selected map feature'[post-commit edit] on an area can not be undone (it is not counted as an action)
- if the photo id is removed the editor forever thinks it is still 'already tagged on this feature'.
- the hover action is temporarily missing until the user clicks on the map.
- Shift + Select selecting multiple objects is not always possible.

Issues observed regardless of state;
- 'tag this photo id on the currently selected map feature' button lags behind with updating the 'is already tagged' state when moving forwards/backwards through a sequence / the button is not present only after switching images/sequences.

Chrome 127.0.6533.120 on Windows 10.

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/0650f303-0e12-4a2a-96e7-4f99a76198ed)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Chrome

---

Other errors

entity not found
```
13id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59 Uncaught Error: entity n-25-n-30 not found
    at Hd.entity (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:30119)
    at Array.n (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:7:6897)
    at t (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6019)
    at r (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:6275)
    at Object.replace (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:9:7429)
    at Object.replace (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:27:23797)
    at d (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8:14013)
    at h (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8:15494)
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at t (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8:10450)
```

n.geometry is not a function
```
id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8 Uncaught TypeError: n.geometry is not a function
    at g (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8:15591)
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at u (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:8:10639)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:2:15186
```

Cannot read properties of undefined (reading 'name')
```
id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:13 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLDivElement.<anonymous> (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:13:1324)
    at HTMLDivElement.<anonymous> (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:2:15186)
```

**Comment by danieldegroot2** [comment]
Seems to resolve the error.
(I included similar errors in the original post for reference)
