### ISSUE TITLE
node v0.12.0 support

### ISSUE THREAD

**Issue by bitner** [openstreetmap/iD#2535]
Running make under node v0.12.0 results in an error in build.js.

bitner@dbspatialtest:/var/www/iDtest/iD$ make
cat css/reset.css css/map.css css/app.css css/feature-icons.css > dist/iD.css
node build.js
/var/www/iDtest/iD/node_modules/d3/node_modules/jsdom/lib/jsdom/level1/core.js:432
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/iDtest/iD/node_modules/d3/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
make: *** [data/data.js] Error 1

**Comment by bhousel** [comment]
I fixed this by upgrading D3.  The newer versions don't have this JSDOM dependency.

Now v0.12 works fine

I also notice when using this version that I see ```util.error: Use console.error instead``` during the uglify-js build step.  But it's a known issue with uglify-js that doesn't affect anything.
