### ISSUE TITLE
Deprecated include of L.Mixin.Events: this property will be removed in future releases

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/iD#4199]
In Chromium just click Edit while Developer tools console is open. You will see:

application-c3070fbc8dbd56a06202821e799cd96c3cff6b3b92151a4c7ce5dd5d4c4db693.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at b (http://www.openstreetmap.org/assets/application-c3070fbc8dbd56a06202821e799cd96c3cff6b3b92151a4c7ce5dd5d4c4db693.js:5:937)
    at Function.f.extend (http://www.openstreetmap.org/assets/application-c3070fbc8dbd56a06202821e799cd96c3cff6b3b92151a4c7ce5dd5d4c4db693.js:5:13989)
    at http://www.openstreetmap.org/assets/application-c3070fbc8dbd56a06202821e799cd96c3cff6b3b92151a4c7ce5dd5d4c4db693.js:9:19620

**Comment by jidanni** [comment]
I'm sorry. This happens even before one clicks edit.
I will "reassign" it ...

**Comment by jidanni** [comment]
OK I'll close it here. And leave it open there.
