### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/iD#4342]
I opened https://osm.wikidata.link/search?q=Poland

It resulted in

```


sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "place_pkey"
DETAIL:  Key (place_id)=(411872) already exists.
 [SQL: 'INSERT INTO place (place_id, osm_type, osm_id, radius, display_name, category, type, place_rank, icon, geom, south, west, north, east, extratags, address, namedetails, item_count, candidate_count, state, override_name, lat, lon, added) VALUES (%(place_id)s, %(osm_type)s, %(osm_id)s, %(radius)s, %(display_name)s, %(category)s, %(type)s, %(place_rank)s, %(icon)s, ST_GeogFromText(%(geom)s), %(south)s, %(west)s, %(north)s, %(east)s, %(extratags)s, %(address)s, %(namedetails)s, %(item_count)s, %(candidate_count)s, %(state)s, %(override_name)s, %(lat)s, %(lon)s, now())'] [parameters: {'state': None, 'icon': 'http://nominatim.openstreetmap.org/images/mapicons/poi_place_village.p.20.png', 'east': '-87.806206', 'address': '{"county": "Brown County", "state": "Wisconsin", "country_code": "us", "hamlet": "Poland", "country": "United States of America"}', 'south': '44.4236052', 'candidate_count': None, 'category': 'place', 'osm_type': 'node', 'west': '-87.846206', 'item_count': None, 'type': 'hamlet', 'namedetails': '{"name": "Poland"}', 'osm_id': '153722470', 'lat': '44.4436052', 'geom': 'POINT(-87.826206 44.4436052)', 'lon': '-87.826206', 'override_name': None, 'radius': 1000, 'display_name': 'Poland, Brown County, Wisconsin, United States of America', 'place_rank': '19', 'place_id': '411872', 'north': '44.4636052', 'extratags': '{}'}]
Traceback (most recent call last)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1547, in handle_exception

    return self.finalize_request(handler(e), from_error_handler=True)

    File "/home/edward/src/2017/osm-wikidata/matcher/view.py", line 148, in exception_handler

    reraise(exc_type, exc_value, tb)

    File "/home/edward/src/2017/osm-wikidata/matcher/view.py", line 141, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/edward/src/2017/osm-wikidata/matcher/view.py", line 1012, in search_results

    osm_id=hit['osm_id']).one_or_none()

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none

    ret = list(self)

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2854, in __iter__

    self.session._autoflush()

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush

    util.raise_from_cause(e)

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb, cause=cause)

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush

    self.flush()

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush

    self._flush(objects)

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush

    transaction.rollback(_capture_exception=True)

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__

    compat.reraise(exc_type, exc_value, exc_tb)

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise

    raise value

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush

    flush_context.execute()

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute

    rec.execute(self)

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute

    uow

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj

    mapper, table, insert)

    File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements

    execute(statement, multiparams)

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute

    return meth(self, multiparams, params)

    File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement

    compiled_sql, distilled_params

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context

    context)

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception

    exc_info

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause

    reraise(type(exception), exception, tb=exc_tb, cause=cause)

    File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise

    raise value.with_traceback(tb)

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context

    context)

    File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute

    cursor.execute(statement, parameters)

    sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "place_pkey" DETAIL: Key (place_id)=(411872) already exists. [SQL: 'INSERT INTO place (place_id, osm_type, osm_id, radius, display_name, category, type, place_rank, icon, geom, south, west, north, east, extratags, address, namedetails, item_count, candidate_count, state, override_name, lat, lon, added) VALUES (%(place_id)s, %(osm_type)s, %(osm_id)s, %(radius)s, %(display_name)s, %(category)s, %(type)s, %(place_rank)s, %(icon)s, ST_GeogFromText(%(geom)s), %(south)s, %(west)s, %(north)s, %(east)s, %(extratags)s, %(address)s, %(namedetails)s, %(item_count)s, %(candidate_count)s, %(state)s, %(override_name)s, %(lat)s, %(lon)s, now())'] [parameters: {'state': None, 'icon': 'http://nominatim.openstreetmap.org/images/mapicons/poi_place_village.p.20.png', 'east': '-87.806206', 'address': '{"county": "Brown County", "state": "Wisconsin", "country_code": "us", "hamlet": "Poland", "country": "United States of America"}', 'south': '44.4236052', 'candidate_count': None, 'category': 'place', 'osm_type': 'node', 'west': '-87.846206', 'item_count': None, 'type': 'hamlet', 'namedetails': '{"name": "Poland"}', 'osm_id': '153722470', 'lat': '44.4436052', 'geom': 'POINT(-87.826206 44.4436052)', 'lon': '-87.826206', 'override_name': None, 'radius': 1000, 'display_name': 'Poland, Brown County, Wisconsin, United States of America', 'place_rank': '19', 'place_id': '411872', 'north': '44.4636052', 'extratags': '{}'}]

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.
```

**Comment by matkoniecz** [comment]
argh wrong repo
