### ISSUE TITLE
CountryCoder Error

### ISSUE THREAD

**Issue by kaligrafy** [openstreetmap/iD#7023]
I get this error with the last commit on master when running ```npm run all```:

```
ERROR: Unexpected token: name "CountryCoder", expected: "punc";
    at JS_Parse_Error.get (eval at <anonymous> (/***/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/***/node_modules/uglify-js/bin/uglifyjs:298:27)
    at run (/***/node_modules/uglify-js/bin/uglifyjs:241:9)
    at Object.<anonymous> (/***/node_modules/uglify-js/bin/uglifyjs:167:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by quincylvania** [comment]
@kaligrafy Thanks, this is #7009.
