### ISSUE TITLE
Searching for lat/long is broken

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/iD#7670]
Steps to reproduce:

1. Enter a latitude,longitude in the search box
2. Click on the location result

Expected: Should jump to the location on the map
Actual: Upon clicking (or hovering) the location result, the following exception happens:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.-1' is not a valid selector.
    at SVGSVGElement.<anonymous> (dist/iD.js:6586:18)
    at Selection.selection_selectAll [as selectAll] (dist/iD.js:6596:32)
    at utilHighlightEntities (dist/iD.js:29813:11)
    at HTMLButtonElement.mouseout (dist/iD.js:94614:14)
    at HTMLButtonElement.<anonymous> (dist/iD.js:7225:17)
```

05925b15f2e430fe170142d5c369c2b33d528f7c is the first bad commit

**Comment by quincylvania** [comment]
@jleedev Thanks for reporting and investigating! Looks like this is only on the `develop` branch and hasn't been released yet…
