### ISSUE TITLE
Multilingual field dropdown does not expand

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9044]
### How to reproduce the issue?

_Related: #8610._

The web console, upon opening iD, returns the following error "**Uncaught TypeError: Cannot read properties of undefined (reading 'en')**", ex.:
```
id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'en')
    at Object.r.languageName (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:6:28105)
    at validationIssue.message (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:13:2415)
    at HTMLSpanElement.<anonymous> (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28:24490)
    at HTMLSpanElement.<anonymous> (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:9937)
    at Selection$1.selection_each [as each] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:6442)
    at Selection$1.selection_html [as html] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:10044)
    at o (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28:24463)
    at Selection$1.selection_call [as call] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:5890)
    at a (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28:23596)
    at Selection$1.selection_call [as call] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:5890)
```
with details, ex.:
```
r.languageName @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:6
message @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:13
(anonymous) @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28
(anonymous) @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
selection_each @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
selection_html @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
o @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28
selection_call @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
a @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28
selection_call @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
l @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:21
selection_call @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
n @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:21
selection_call @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4
reRender @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:21
(anonymous) @ id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:28
```

If an object is created with `name:xx` (i.e. `name:fr`), the following happens;
1. Multilingual field dropdown arrow has a "can't expand" symbol.
2. Multilingual field dropdown, when the field/arrow is clicked, won't expand. It only displays a grey background (normal), slither of dropdown and its shadow.

### Screenshot(s) or anything else?

With issue
![image](https://user-images.githubusercontent.com/67521919/159482555-deab192e-afd5-4f18-81cd-84803ba9de51.png)
![image](https://user-images.githubusercontent.com/67521919/159482570-c0051f96-5d23-44a9-bd7c-2bc05720907f.png)

Without issue (gaborhodi#7079 on id channel of OSM World Discord)
![image](https://user-images.githubusercontent.com/67521919/159483118-239cff57-a3ba-4682-90c3-c5385eda3f85.png)

* The only other web console errors are for #9045 
* There is no wikidata (or brand) tag prohibiting the action. I've also tried this with empty objects (nodes, ways at least).
* Leaving the `name:xx` field empty does not matter.
* On the RapiD version, I do not get a "can't expand" icon on the dropdown arrow, but the dropdown still does not expand properly.
* I have not tried Microsoft Edge, I can't try Safari.
* Language(s): At least Dutch.

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.com, RapiD version at mapwith.ai/rapid

### Which browsers are you seeing this problem on?

Firefox, Chrome

**Comment by tyrasd** [comment]
I can confirm that the mouse cursor is showing the dropdown arrow as disabled/forbidden. But clicking on it still opens the dropdown, interestingly.

> Uncaught TypeError: Cannot read properties of undefined (reading 'en')

I don't see this exception in the logs, but maybe that one was unrelated and caused by the other linked bug.
