### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by ZeeshanZulfiqarAli** [openstreetmap/iD#9101]
I am unable to build on my local machine using `npm run all` command, which throws an error related to not being able to find icon in font-awesome. It was working fine a few hours back ( if that helps ).

### How to reproduce the issue?

Run `npm run all` command and you'll see the following error:

```
zeeshan@Zeeshans-MacBook-Air iD % npm run all

> iD@2.21.0-dev all
> run-s clean build dist


> iD@2.21.0-dev clean
> shx rm -f dist/esbuild.json dist/*.js dist/*.map dist/*.css dist/img/*.svg


> iD@2.21.0-dev build
> run-s build:css build:data build:js


> iD@2.21.0-dev build:css
> node scripts/build_css.js


🏗   Building css...
👍  css built: 134.63ms


> iD@2.21.0-dev build:data
> shx mkdir -p dist/data && node scripts/build_data.js


🏗   Building data...
Error: No FontAwesome icon for fas-th-list
TypeError: Cannot read properties of undefined (reading 'html')
    at /Users/zeeshan/work/iD/scripts/build_data.js:229:75
    at Array.forEach (<anonymous>)
    at writeFaIcons (/Users/zeeshan/work/iD/scripts/build_data.js:224:23)
    at /Users/zeeshan/work/iD/scripts/build_data.js:114:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 9)

ERROR: "build:data" exited with 1.
ERROR: "build" exited with 1.
```

### Screenshot(s) or anything else?

Currently tested on `develop` branch

**Comment by arch0345** [comment]
Build seems to work if you change the version of these four dependencies in `package.json` to `~6.1.0`:
https://github.com/openstreetmap/iD/blob/ce136d0144487bc3c8fb569910958865860559a3/package.json#L71-L74
