### ISSUE TITLE
Specific mapping of empty lines causes three empty items in right click menu

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/iD#9125]
### How to reproduce the issue?

It seems creating this shape and selecting all the lines creates three empty items in the right click menu.
The buttons still work, it is only the icons which are not being displayed.

I came across this when specifying the position of a wayside cross with some empty guiding lines.
(ignore empty line in bottom right I used to check if right click menu was still working normally otherwise.)

In the dev console, I can see the empty items are straighten, copy and delete.

I also get this error
`id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:9`
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at r (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:9:6977)
    at Function.a.disabled (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:9:7739)
    at Function.r.disabled (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:31:22027)
    at Function.r.tooltip (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:31:22220)
    at HTMLButtonElement.<anonymous> (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:17:32206)
    at Selection$1.selection_each [as each] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:6442)
    at s (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:17:32145)
    at Selection$1.selection_call [as call] (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:4:5890)
    at Object.o.showEditMenu (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:29:25759)
    at u (id-23b658959c0f1203ad860ee3123c0e2b39c6c5c30a6f2897b838961414eea0c8.js:31:6675)
```

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/67521919/169663899-c13c28a3-ef2b-4311-b6e8-6cfe4d7e9404.png)
![image](https://user-images.githubusercontent.com/67521919/169663907-547b3db4-3623-4559-8c14-91c4a527c80f.png)
![image](https://user-images.githubusercontent.com/67521919/169663914-4ad4d7a7-fca5-4c40-8b2c-96976d85a677.png)
![image](https://user-images.githubusercontent.com/67521919/169664147-26820cb5-27fe-46e8-ae57-f523dcb843cd.png)
![image](https://user-images.githubusercontent.com/67521919/169664154-dc063318-a5f0-4651-9de6-2d6e5efa6db2.png)

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
I assume this was probably fixed in the meantime. If you can still get the bug, please comment

**Comment by danieldegroot2** [comment]
This issue still partially occurs on iD 2.39.5

To reproduce
1. Draw inverted U (would have followed wall around monument on aerial);
however not something you should do, so it is an edge case; using square instead this seems to not happen
2. Draw horizontal line connecting bottom ends
3. Draw vertical line between midpoints
4. Select all three lines
5. Right click. Icons are empty => Now, icons are no longer empty, but the bar appears behind the right toolbar.
When closing the right click menu, it is shortly black before disappearing.

<img width="3829" height="1673" alt="Image" src="https://github.com/user-attachments/assets/50f21905-9cf5-443d-bdc8-0e40dec8bcae" />

The console error still occurs

Chrome 146.0.7680.165

<details>
```
straighten_way.js:62 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at allNodes (straighten_way.js:62:17)
    at action.disabled (straighten_way.js:128:21)
    at operation2.disabled (straighten.js:96:30)
    at HTMLButtonElement.<anonymous> (edit_menu.js:143:57)
    at HTMLButtonElement.<anonymous> (classed.js:58:12)
    at Selection.each_default [as each] (each.js:5:37)
    at Selection.classed_default [as classed] (classed.js:71:15)
    at editMenu (edit_menu.js:143:14)
    at Selection.call_default [as call] (call.js:4:12)
    at ui.showEditMenu (init.js:669:14)
```
</details>

Firefox 149.0

<details>
```
Uncaught TypeError: can't access property 0, nextWay is undefined
    allNodes straighten_way.js:62
    disabled straighten_way.js:128
    disabled straighten.js:96
    editMenu edit_menu.js:143
    classedFunction classed.js:58
    each_default each.js:5
    classed_default classed.js:71
    editMenu edit_menu.js:143
    call_default call.js:4
    showEditMenu init.js:669
    processClick select.js:373
    click select.js:249
    contextmenu select.js:194
    contextListener on.js:3
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:415
    call_default call.js:4
    install context.js:343
    enter select.js:260
    enter context.js:319
    processClick select.js:336
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    enter select.js:260
    enter context.js:319
    processClick select.js:336
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    enter select.js:260
    enter context.js:319
    processClick select.js:320
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    enter browse.js:45
    enter context.js:319
    processClick select.js:366
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
[straighten_way.js:62:17](https://www.openstreetmap.org/assets/@openstreetmap/id/modules/actions/straighten_way.js)
    allNodes straighten_way.js:62
    disabled straighten_way.js:128
    disabled straighten.js:96
    editMenu edit_menu.js:143
    classedFunction classed.js:58
    each_default each.js:5
    classed_default classed.js:71
    editMenu edit_menu.js:143
    call_default call.js:4
    showEditMenu init.js:669
    processClick select.js:373
    click select.js:249
    contextmenu select.js:194
    contextListener on.js:3
    (Async: EventListener.handleEvent)
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:415
    call_default call.js:4
    install context.js:343
    forEach self-hosted:145
    enter select.js:260
    enter context.js:319
    processClick select.js:336
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    (Async: EventListener.handleEvent)
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    forEach self-hosted:145
    enter select.js:260
    enter context.js:319
    processClick select.js:336
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    (Async: EventListener.handleEvent)
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    forEach self-hosted:145
    enter select.js:260
    enter context.js:319
    processClick select.js:320
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    (Async: EventListener.handleEvent)
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
    call_default call.js:4
    install context.js:343
    forEach self-hosted:145
    enter browse.js:45
    enter context.js:319
    processClick select.js:366
    click select.js:249
    pointerup select.js:156
    contextListener on.js:3
    (Async: EventListener.handleEvent)
    onAdd on.js:42
    each_default each.js:5
    on_default on.js:65
    behavior select.js:401
```
</details>

Edge 146.0.3856.84

<details>
```
straighten_way.js:62 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at allNodes (straighten_way.js:62:17)
    at action.disabled (straighten_way.js:128:21)
    at operation2.disabled (straighten.js:96:30)
    at HTMLButtonElement.<anonymous> (edit_menu.js:143:57)
    at HTMLButtonElement.<anonymous> (classed.js:58:12)
    at Selection.each_default [as each] (each.js:5:37)
    at Selection.classed_default [as classed] (classed.js:71:15)
    at editMenu (edit_menu.js:143:14)
    at Selection.call_default [as call] (call.js:4:12)
    at ui.showEditMenu (init.js:669:14)
allNodes @ straighten_way.js:62
action.disabled @ straighten_way.js:128
operation2.disabled @ straighten.js:96
(anonymous) @ edit_menu.js:143
(anonymous) @ classed.js:58
each_default @ each.js:5
classed_default @ classed.js:71
editMenu @ edit_menu.js:143
call_default @ call.js:4
ui.showEditMenu @ init.js:669
processClick @ select.js:373
click @ select.js:249
contextmenu @ select.js:194
(anonymous) @ on.js:3
```
</details>
