### ISSUE TITLE
Syntax Error on Trying to install the project.

### ISSUE THREAD

**Issue by DanBrown47** [openstreetmap/iD#9481]
### How to reproduce the issue?

Issue
--

1) Clone the project 🆗  _ Release v2.24.1

> git clone --depth=1 https://github.com/openstreetmap/iD.git  
> or on
>  https://github.com/openstreetmap/iD/releases/tag/v2.24.1

2) Run npm install 🆗 
3) Run  npm run all 🚫 

This will return with an error 
```
> iD@2.24.1 build:js
> node config/esbuild.config.mjs

file:///home/nero/osm/iD-2.24.1/config/esbuild.config.mjs:8
const context = await esbuild.context({
                ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
ERROR: "build:js" exited with 1.
ERROR: "build" exited with 1.
```

PS : Tested on docker as well as a AWS EC2 Instance to rule out the possibility of any system specific issue

Using 
--

> Ubuntu 22.04
> NPM 8.5.1
> Node v12.22.9

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/45515141/215490881-7c44cf86-2f79-4874-9562-717d73eb3058.png)

### What version numbers does this issue effect?

2.24.1

### Which browsers are you seeing this problem on?

Other (please specify)

**Comment by DanBrown47** [comment]
The Issue is fixed on updating Node to latest versions
